### ISSUE TITLE
bump pytest version

### ISSUE THREAD

**Issue by ortenburger** [aws-samples/asynchronous-event-processing-api-gateway-lambda-cdk#11]
Currently in .projenrc.py there is pytest==7.2.1 specified, this results after running 'npx projen' in a requirements-dev.txt with two different pytest lines. pytest==7.2.1 and pytest==7.4.3
The fix is to just bump the version in .projenrc.py tp pytest==7.4.3

Best

**Comment by andreameroni** [comment]
Thanks for your comment - Fixed as suggested
